### ISSUE TITLE
Fault: <unprintable Fault object> when creating database

### ISSUE THREAD

**Issue by askz** [odoo-latam/odoo-infrastructure#34]
Hi ! I have this error when I try to create a database, I found that it's when the base module are installed. But zero module get installed in the db at the end. The DB is created but not the modules

> 2016-04-26 14:13:31,965 4849 INFO erp-businessagile-eu openerp.addons.infrastructure.models.database: Installing modules: [u'database_tools', u'web_support_client', u'server_mode', u'web_support_client_issue']
> 
> Traceback (most recent call last):
>   File "/opt/odoo/odoo-infra/parts/odoo/openerp/http.py", line 539, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/opt/odoo/odoo-infra/parts/odoo/openerp/http.py", line 576, in dispatch
>     result = self._call_function(*_self.params)
>   File "/opt/odoo/odoo-infra/parts/odoo/openerp/http.py", line 312, in _call_function
>     return checked_call(self.db, *args, *_kwargs)
>   File "/opt/odoo/odoo-infra/parts/odoo/openerp/service/model.py", line 118, in wrapper
>     return f(dbname, _args, *_kwargs)
>   File "/opt/odoo/odoo-infra/parts/odoo/openerp/http.py", line 309, in checked_call
>     return self.endpoint(_a, *_kw)
>   File "/opt/odoo/odoo-infra/parts/odoo/openerp/http.py", line 805, in __call__
>     return self.method(_args, *_kw)
>   File "/opt/odoo/odoo-infra/parts/odoo/openerp/http.py", line 405, in response_wrap
>     response = f(_args, *_kw)
>   File "/opt/odoo/odoo-infra/parts/odoo/addons/web/controllers/main.py", line 948, in call_button
>     action = self._call_kw(model, method, args, {})
>   File "/opt/odoo/odoo-infra/parts/odoo/addons/web/controllers/main.py", line 936, in _call_kw
>     return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
>   File "/opt/odoo/odoo-infra/parts/odoo/openerp/api.py", line 268, in wrapper
>     return old_api(self, _args, *_kwargs)
>   File "/opt/odoo/odoo-infra/parts/odoo/openerp/api.py", line 439, in old_api
>     result = new_api(recs, _args, *_kwargs)
>   File "/opt/odoo/odoo-infra/parts/odoo/openerp/api.py", line 443, in new_api
>     result = [method(rec, _args, *_kwargs) for rec in self]
>   File "/opt/odoo/odoo-infra/parts/odoo-infrastructure/infrastructure/models/database.py", line 821, in create_db
>     self.install_base_modules()
>   File "/opt/odoo/odoo-infra/parts/odoo/openerp/api.py", line 266, in wrapper
>     return new_api(self, _args, *_kwargs)
>   File "/opt/odoo/odoo-infra/parts/odoo-infrastructure/infrastructure/models/database.py", line 581, in install_base_modules
>     self.install_modules(base_modules)
>   File "/opt/odoo/odoo-infra/parts/odoo/openerp/api.py", line 266, in wrapper
>     return new_api(self, _args, *_kwargs)
>   File "/opt/odoo/odoo-infra/parts/odoo-infrastructure/infrastructure/models/database.py", line 591, in install_modules
>     client.install(_modules_names)
>   File "/opt/odoo/odoo-infra/eggs/ERPpeek-1.6.3-py2.7.egg/erppeek.py", line 819, in install
>     return self._upgrade(modules, button='button_install')
>   File "/opt/odoo/odoo-infra/eggs/ERPpeek-1.6.3-py2.7.egg/erppeek.py", line 781, in _upgrade
>     self.execute('ir.module.module', button, ids)
>   File "/opt/odoo/odoo-infra/eggs/ERPpeek-1.6.3-py2.7.egg/erppeek.py", line 712, in execute
>     res = self._execute(obj, method, *params)
>   File "/opt/odoo/odoo-infra/eggs/ERPpeek-1.6.3-py2.7.egg/erppeek.py", line 402, in <lambda>
>     wrapper = lambda s, *args: s._dispatch(name, args)
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1591, in __request
>     verbose=self.__verbose
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
>     return self.single_request(host, handler, request_body, verbose)
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1306, in single_request
>     return self.parse_response(response)
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1482, in parse_response
>     return u.close()
>   File "/usr/lib/python2.7/xmlrpclib.py", line 794, in close
>     raise Fault(_*self._stack[0])
> Fault: <unprintable Fault object>

**Comment by askz** [comment]
My bad, this was a dependancy problem, a module wasn't there. Sorry !
